# Use the official Python image from the Docker Hub
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Copy only the requirements file to leverage Docker cache
COPY chat_with_congress/requirements.txt /app/requirements.txt
COPY .env /app/.env
# Install system dependencies and Python packages
RUN apt-get update && apt-get install -y apt-transport-https ca-certificates gnupg curl git vim net-tools build-essential \
    && echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list \
    && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg \
    && apt-get update -y && apt-get install -y google-cloud-cli \
    && pip install --no-cache-dir -r requirements.txt \
    && apt-get clean

ENV PYTHONPATH=/app    
# Copy the rest of the application code to the working directory
# Copy the .env file to the container


COPY . .

# Expose the port that the app runs on
EXPOSE 8000

# Command to run the FastAPI server
CMD ["uvicorn", "chat_with_congress.app.api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
